<?php
session_start();
require_once(dirname(__FILE__) . '/db_connection/dbconn.php');
// To send HTML mail, the Content-type header must be set

$user_firstname = $_SESSION['user_firstname'];
$user_lastname = $_SESSION['user_lastname'];
$user_saving_report = $_SESSION['user_saving_report'];
$user_insurance_report = $_SESSION['user_insurance_report'];
$user_salary_report = $_SESSION['user_salary_report'];
$user_saving_calc = $_SESSION['user_saving_calc'];
$user_overall_financial_health_score = $_SESSION['user_overall_financial_health_score'];
$user_email = $_SESSION['user_email'];

$disclaimer = "<em><Strong>Disclaimer</Strong> -Any advice generated by healthyfinancecheck.com algorithms should not be considered as professional insurance or investement advice.
Healthyfinancecheck.com is not liable for any loss caused, whether due to negligence or otherwise arising from the use of, or reliance on, the information provided directly or indirectly, by use of this website.</em>";

$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

$subject = "Your Financial Health Analysis Results";
$body = "Hi <strong>$user_firstname $user_lastname,</strong> ";
$body .= nl2br("\nThank you for taking the Financial Health Check.\n");
$body .= nl2br("\nYour results are as follows\n");
$body .= nl2br("<strong>Overall Score: $user_overall_financial_health_score </strong>\n");
$body .= "\n<strong>Savings: </strong>";
$body .= nl2br("\nIdeal Savings: </strong><span style ='color: #4CAF50;'>$user_saving_calc </span></strong>");
$body .= nl2br("\n$user_saving_report\n");
$body .= nl2br("\n<strong>Insurance: </strong>");
$body .= nl2br("\n$user_insurance_report\n");
$body .= nl2br("\n<strong>Salary:</strong>");
$body .= nl2br("\n$user_salary_report\n");
$body .= nl2br("\n$disclaimer");
$sender = "From:raphael.chengxuyuan@gmail.com";

//Validate first (necessary??)
if(empty($user_firstname)||empty($user_email))
{
    echo "Name and email are mandatory!";
    exit;
}

//malicious attempt
if(IsInjected($user_email))
{
    echo "Bad email value!";
    exit;
}

//if(mail($receiver, $subject, $body, $sender,$headers)){
if(mail($user_email, $subject, $body,$headers)){
    echo "Email sent successfully to $user_email";
}else{
    echo "Sorry, failed while sending mail!";
}

function IsInjected($str)
{
  $injections = array('(\n+)',
              '(\r+)',
              '(\t+)',
              '(%0A+)',
              '(%0D+)',
              '(%08+)',
              '(%09+)'
              );
  $inject = join('|', $injections);
  $inject = "/$inject/i";
  if(preg_match($inject,$str))
    {
    return true;
  }
  else
    {
    return false;
  }
}
//redirect user after email to their results page (should it go to home page?)
header('Location: index.php');exit();
?>
