<?php
require_once('header.php');
if($_SESSION['user_ip'] == ''){header("Location: index.php");} //Is IP available?
$fin_health_resp_ip_addr = $_SESSION['user_ip'];

//Is new user?
$fin_health_resp_user_check = $conn->prepare("SELECT * FROM fin_health_test_resp WHERE fin_health_resp_ip_addr='$fin_health_resp_ip_addr'");
$fin_health_resp_user_check->execute();
$fin_health_resp_result = $fin_health_resp_user_check->fetch(PDO::FETCH_ASSOC);

//Set variables returned from server call
$fin_health_resp_married = $fin_health_resp_result['fin_health_resp_married'];
$fin_health_resp_savings = intval($fin_health_resp_result['fin_health_resp_savings']);
$fin_health_resp_salary = intval($fin_health_resp_result['fin_health_resp_salary']);
$fin_health_resp_investment_ratio = $fin_health_resp_result['fin_health_resp_investment_ratio'];
$fin_health_resp_age = intval($fin_health_resp_result['fin_health_resp_age']);
$fin_health_resp_children_count = intval($fin_health_resp_result['fin_health_resp_children_count']);
$fin_health_resp_profession =$fin_health_resp_result['fin_health_resp_profession'];
$fin_health_resp_profession_time = $fin_health_resp_result['fin_health_resp_profession_time'];
$fin_health_resp_insurance = intval($fin_health_resp_result['fin_health_resp_insurance']);
$fin_health_resp_youngest = intval($fin_health_resp_result['fin_health_resp_youngest']);
$fin_health_resp_mortgage = intval($fin_health_resp_result['fin_health_resp_mortgage']);
$fin_health_resp_credit_card_debt = intval($fin_health_resp_result['fin_health_resp_credit_card_debt']);
$fin_health_resp_other_debt = intval($fin_health_resp_result['fin_health_resp_other_debt']);
$fin_health_resp_gender = $fin_health_resp_result['fin_health_resp_gender'];
$fin_health_resp_country = $fin_health_resp_result['fin_health_resp_country'];
$fin_health_resp_getapi_country = $fin_health_resp_result['fin_health_resp_getapi_country'];

//put in a  function and file
$disclaimer = "<em><Strong>Disclaimer</Strong> -Any advice generated by healthyfinancecheck.com algorithms should not be considered as professional insurance or investement advice.
Healthyfinancecheck.com is not liable for any loss caused, whether due to negligence or otherwise arising from the use of, or reliance on, the information provided directly or indirectly, by use of this website.</em>";

$currency_convert = conversion_variable($fin_health_resp_country);
list($conversion_rate) = $currency_convert;

//Salary Percentile TT based on Age, Gender. Done in USD (Data sstored in USD)
$stmt = $conn->prepare("CALL GetSalaryPercentile(:income,:age,:gender,:region)");
$stmt->bindParam(':income', $fin_health_resp_salary, PDO::PARAM_INT);
$stmt->bindParam(':age',$fin_health_resp_age,PDO::PARAM_INT);
$stmt->bindParam(':gender',$fin_health_resp_gender,PDO::PARAM_STR);
$stmt->bindParam(':region',$fin_health_resp_country,PDO::PARAM_STR);
$stmt->execute();
$sal_percentile = $stmt->fetch();
$fin_health_resp_sal_percentile = intval($sal_percentile[0]);

//Convert $$ amounts to user's region currency.
$fin_health_resp_savings = $fin_health_resp_savings * $conversion_rate;
$fin_health_resp_salary = $fin_health_resp_salary * $conversion_rate; //no conversion needed
$fin_health_resp_mortgate= $fin_health_resp_mortgage * $conversion_rate;
$fin_health_resp_insurance = $fin_health_resp_insurance * $conversion_rate;
$fin_health_resp_credit_card_debt = $fin_health_resp_credit_card_debt * $conversion_rate;
$fin_health_resp_other_debt = $fin_health_resp_other_debt * $conversion_rate;


$saving_health_result = saving_health($fin_health_resp_savings, $fin_health_resp_salary,$fin_health_resp_age);
list($saving_calculation, $projected_saving, $current_saving) = $saving_health_result;
//var_dump($current_saving);
$user_savings = new CurrencyFormat();
$user_savings->set_region_dollar_amt($current_saving);
$user_savings-> get_region_dollar_amt();

$user_projected_saving = new CurrencyFormat();
$user_projected_saving->set_region_dollar_amt($projected_saving);
$user_projected_saving->get_region_dollar_amt();

$saving_analysis = savings_report($fin_health_resp_age,$projected_saving, $current_saving,$fin_health_resp_salary,$fin_health_resp_investment_ratio);
list($saving_report_detail) = $saving_analysis;

$fin_health_resp_inv = 0; //null for now 18/9/2022

$insurance_health_result = insurance_health($fin_health_resp_insurance,$fin_health_resp_age,$fin_health_resp_children_count,$fin_health_resp_youngest,$fin_health_resp_salary,$fin_health_resp_credit_card_debt,$fin_health_resp_other_debt,$fin_health_resp_savings,$fin_health_resp_married);
list($insurance_calculation,$recommended_insurance, $current_insurance) = $insurance_health_result;

$user_insurance = new CurrencyFormat();
$user_insurance->set_region_dollar_amt($current_insurance);
$user_insurance->get_region_dollar_amt();

$user_recommended_insurance = new CurrencyFormat();
$user_recommended_insurance->set_region_dollar_amt($recommended_insurance);
$user_recommended_insurance->get_region_dollar_amt();

$insurance_analysis = insurance_report($fin_health_resp_insurance, $recommended_insurance,$fin_health_resp_salary, $fin_health_resp_children_count);
list($insurance_report_detail) = $insurance_analysis;


$salary_health_result = salary_health($fin_health_resp_salary,$fin_health_resp_sal_percentile);
list($salary_calculation,$recommended_salary,$current_salary) = $salary_health_result;

$user_salary = new CurrencyFormat();
$user_salary->set_region_dollar_amt($fin_health_resp_salary);
$user_salary->get_region_dollar_amt();

$salary_analysis = salary_report($fin_health_resp_salary,$salary_calculation,$fin_health_resp_age,$fin_health_resp_gender,$fin_health_resp_sal_percentile);
list($salary_report_detail) = $salary_analysis;

$overall_fin_health = overall_health($salary_calculation,$insurance_calculation,$saving_calculation);
echo $overall_fin_health;

$financial_service_contact = user_contact_request ($fin_health_resp_country);
list($contactable_user) = $financial_service_contact;

?>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="finanalysis.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>
  $(document).ready(function() {
    $width = $("#mySavingBar").data('width');
    $("#mySavingBar").css("width", $width + "%");

    $width = $("#myInvestmentsBar").data('width');
    $("#myInvestmentsBar").css("width", $width + "%");

    $width2 = $("#myInsuranceBar").data('width');
    $("#myInsuranceBar").css("width", $width2 + "%");

    $width3 = $("#myIncomeBar").data('width');
    $("#myIncomeBar").css("width", $width3 + "%");

  });
  </script>
</head>

<body>
  <!-- wrapper starts -->
  <div class="wrapper">
    <div class="wrapper_inner">
      <h1 class="heading">Financial Health Results</h1>

      <!-- savings box -->
      <div class="result_box">
        <h3 class="hd text-center">Saving Health</h3>
        <p>Saving health considering age & income</p>
        <div class="row align-items-center">
          <div class="bar_main col-sm-11 col-9">
            <div id="mySaving" class="bar">
              <div id="mySavingBar" data-width="<?php echo $saving_calculation;?>"></div>
            </div>
          </div>
          <div class="percent col-sm-1 col-3">
            <?php echo $saving_calculation; ?> %
          </div>
        </div>
        <div class="box_analysis">
          <h3>Reported Savings: <?php echo $user_savings; ?> </h3>
          <h3>Ideal Savings: <?php echo $user_projected_saving; ?> </h3>
          <?php echo $saving_report_detail; ?>
        </div>
      </div>

      <!-- insurance box -->
      <div class="result_box">
        <h3 class="hd text-center">Insurance Health</h3>
        <p>Insurance health considering age & family size
        </p>
        <div class="row align-items-center">
          <div class="bar_main col-sm-11 col-9">
            <div id="myInsurance" class="bar">
              <div id="myInsuranceBar" data-width="<?php echo $insurance_calculation; ?>"></div>
            </div>
          </div>
          <div class="percent col-sm-1 col-3">
            <?php echo $insurance_calculation; ?> %
          </div>
        </div>
        <div class="box_analysis">
          <h3>Reported Life Insurance: <?php echo $user_insurance; ?> </h3>
          <h3>Ideal Life Insurance: <?php echo ($recommended_insurance < 0) ? "Adequate Coverage": $user_recommended_insurance; ?> </h3>
          <?php echo $insurance_report_detail;?>
        </div>

      </div>

      <!-- income box -->
      <div class="result_box">
        <h3 class="hd text-center">Income Health</h3>
        <p>Income ranking as a percentile based on gender, age, country</p>
        <div class="row align-items-center">
          <div class="bar_main col-sm-11 col-9">
            <div id="myIncome" class="bar">
              <div id="myIncomeBar" data-width="<?php echo $salary_calculation; ?>"></div>
            </div>
          </div>
          <div class="percent col-sm-1 col-3">
            <?php echo ($salary_calculation == 100) ? "No Region Data" : $salary_calculation . '%'; ?>
          </div>
        </div>
        <div class="box_analysis">
          <h3>Your Reported Income: <?php echo $user_salary; ?> </h3>
          <?php echo $salary_report_detail;?>
        </div>
      </div>
      <div class="overall_score">
      Overall Score <br> <?php echo $overall_fin_health; ?> %

      </div>
    <div class="disclaimer"style="font-size:.75em;">
      <?php echo $disclaimer;?>
    </div>
    </div>
  </div>
  <!-- wrapper ends -->
  <!-- buttons -->
  <div class="links">
    <a class="button" id="myBtn">Get Full Personal Report</a>
    <a href="index.php" class="button">Return to Home</a>
  </div>

  <!-- The Modal -->
  <div id="myModal" class="modal">

    <!-- Modal content -->
  <!--  <div class="result_box col-lg-6 col-sm-8 col-10">-->

    <div class="modal-content">
      <span class="close">&times;</span>
      <form method="post" action="post_fin_health_report_data.php" class="form-container">
      <header>
          <h1>Email Financial Health Report</h1>
      </header>

      <input class="email" type="text" autocomplete="off" placeholder="Email" name="user_email" required>

      <input class="firstname" type="text" autocomplete="off" placeholder="First Name" name="user_firstname" required>

      <?php echo $contactable_user; ?>
      <!--
      <input class="lastname" type="text" autocomplete="off" placeholder="Enter Last Name" name="user_lastname" required>
      <input class="telephone" type="text" autocomplete="off" placeholder="Enter Phone Number" name="user_telephone">
    -->
      <!--<br>
      <input class="contact" type="checkbox" name="user_resp_yes_contact" value="true" checked>
      <label for="myinput" class="indented-checkbox-text">Yes. I would like to be contacted by a financial services professional.</label>
    -->
      <br>
      <input class="emailsubscription" type="checkbox" name="user_resp_yes_email_list" value="true" checked>
      <label for="myinput" class="indented-checkbox-text">Yes. Send me financial health articles, tips and updates.</label>

      <!--user report-->
       <input type="hidden" name="user_saving_report" value="<?php echo $saving_report_detail; ?>">
       <input type="hidden" name="user_insurance_report" value="<?php echo $insurance_report_detail; ?>">
       <input type="hidden" name="user_salary_report" value="<?php echo $salary_report_detail; ?>">
       <!--user potential opportunities data-->
       <input type="hidden" name="user_gender" value="<?php echo $fin_health_resp_gender; ?>">
       <input type="hidden" name="user_age" value="<?php echo $fin_health_resp_age; ?>">
       <input type="hidden" name="user_apiresult_country" value="<?php echo $fin_health_resp_getapi_country; ?>">
       <input type="hidden" name="user_country" value="<?php echo $fin_health_resp_country; ?>">
       <input type="hidden" name="user_married" value="<?php echo $fin_health_resp_married; ?>">
       <input type="hidden" name="user_children_count" value="<?php echo $fin_health_resp_children_count; ?>">
       <input type="hidden" name="user_profession" value="<?php echo $fin_health_resp_profession; ?>">
       <input type="hidden" name="user_profession_time" value="<?php echo $fin_health_resp_profession_time; ?>">
       <input type="hidden" name="user_salary" value="<?php echo $fin_health_resp_salary; ?>">
       <input type="hidden" name="user_mortgage_monthly" value="<?php echo $fin_health_resp_mortgage; ?>">
       <input type="hidden" name="user_savings" value="<?php echo $current_saving; ?>">
       <input type="hidden" name="user_savings_recommendation" value="<?php echo $user_projected_saving; ?>">
       <input type="hidden" name="user_saving_score" value="<?php echo $saving_calculation; ?>">
       <input type="hidden" name="user_credit_card_debt" value="<?php echo $fin_health_resp_credit_card_debt; ?>">
       <input type="hidden" name="user_other_debt" value="<?php echo $fin_health_resp_other_debt; ?>">
       <input type="hidden" name="user_investment_ratio" value="<?php echo $fin_health_resp_investment_ratio; ?>">
       <input type="hidden" name="user_investment_recommendation" value="<?php echo $fin_health_resp_inv; ?>"><!--null for nwo-->
       <input type="hidden" name="user_insurance" value="<?php echo $fin_health_resp_insurance; ?>">
       <input type="hidden" name="user_insurance_recommendation" value="<?php echo $recommended_insurance; ?>">
       <input type="hidden" name="user_insurance_score" value="<?php echo $insurance_calculation; ?>">
       <input type="hidden" name="user_overall_fin_health" value="<?php echo $overall_fin_health; ?>">


      <button type="submit" class="btn">Submit</button>

      </form>
    </div> <!--end modal_content div -->
  </div> <!--end myModal div -->

<!--modal js -->
<script>
//clear the form on refresh
window.onload = function(){
    document.getElementById("form-container").innerHTML = "";
}

// Get the modal
var modal = document.getElementById("myModal");

var footer = document.getElementsByClassName("footer");

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
  modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>
</body>
</html>
